### ISSUE TITLE
Battery widget throws error since 89ae530 (autodetection function for batteries)

### ISSUE THREAD

**Issue by wimstefan** [lcpz/lain#397]
`awesome -v`
awesome v4.2-357-ge7251011-dirty (Human after all)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.0

`lua -v`
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio

* expected behavior
Showing battery status or the ac status if there's no battery present.

* actual behavior
I get this error message:
`stack traceback:
        [C]: in function 'format'
        /home/swimmer/.config/awesome/lain/widget/bat.lua:144: in function 'func'
        /usr/share/awesome/lib/gears/object.lua:123: in function 'emit_signal'
        /home/swimmer/.config/awesome/lain/helpers.lua:96: in function 'newtimer'
        /home/swimmer/.config/awesome/lain/widget/bat.lua:211: in function 'bat'
        /home/swimmer/.config/awesome/rc.lua:386: in main chunk
error: /home/swimmer/.config/awesome/lain/widget/bat.lua:144: bad argument #3 to 'format' (string expected, got nil)`

* steps to reproduce the problem
The lines regarding the battery widget config are 
``` lua
local widget_power = lain.widget.bat({
      battery = "BAT*",
      notify = "on",
      settings = function()
        if bat_now.status == "N/A" then
          power_icon = markup.font(beautiful.icon_font, "") .. markup.font(beautiful.font, "  AC ")
        elseif bat_now.status == "Charging" and tonumber(bat_now.perc) <= 70 then
          power_icon = markup.font(beautiful.icon_font, "") .. markup.font(beautiful.font, " " .. bat_now.perc .."%  ")
        elseif bat_now.status == "Charging" and tonumber(bat_now.perc) >= 70 then
          power_icon = markup.font(beautiful.icon_font, "") .. markup.font(beautiful.font, " " .. bat_now.perc .."%  ")
        else
          if tonumber(bat_now.perc) <= 10 then
            power_icon = markup.font(beautiful.icon_font, "") .. markup.font(beautiful.font, " " .. bat_now.perc .. "%  ")
          elseif tonumber(bat_now.perc) <= 30 then
            power_icon = markup.font(beautiful.icon_font, "") .. markup.font(beautiful.font, " " .. bat_now.perc .. "%  ")
          elseif tonumber(bat_now.perc) <= 50 then
            power_icon = markup.font(beautiful.icon_font, "") .. markup.font(beautiful.font, " " .. bat_now.perc .. "%  ")
          elseif tonumber(bat_now.perc) <= 70 then
            power_icon = markup.font(beautiful.icon_font, "") .. markup.font(beautiful.font, " " .. bat_now.perc .. "%  ")
          elseif tonumber(bat_now.perc) <= 85 then
            power_icon = markup.font(beautiful.icon_font, "") .. markup.font(beautiful.font, " " .. bat_now.perc .. "%  ")
          else
            power_icon = markup.font(beautiful.icon_font, "") .. markup.font(beautiful.font, " " .. bat_now.perc .. "%  ")
          end
        end
        widget:set_markup(markup.font(beautiful.font, power_icon))

        bat_notification_low_preset = {
          title = "Battery low",
          text = "Plug the cable!",
          timeout = 15,
          fg = beautiful.red1,
          bg = beautiful.black2
        }
        bat_notification_critical_preset = {
          title = "Battery exhausted",
          text = "Shutdown imminent",
          timeout = 15,
          fg = beautiful.white1,
          bg = beautiful.black2
        }
      end
})
```

**Comment by lcpz** [comment]
I forgot to add a failsafe `ac` when you don't define one. Should be solved in latest commit.

By the way, don't use wildcards, unless you really have a dir named `BAT*`.

PS: can you try not defining `battery` to see how autodetection works on your machine?

**Comment by wimstefan** [comment]
> I forgot to add a failsafe ac when you don't define one. Should be solved in latest commit.

Thanks a lot for that swift reaction! I pulled the latest commit immediately. Unfortunately it didn't solve my problem :-/

> By the way, don't use wildcards, unless you really have a dir named BAT*.

Hm? I got that information straight from the wiki:
"The widget will try to autodetect battery, batteries and ac. If something goes wrong, you will have to define them manually. In that case, you only have to define one between battery and batteries. If you have one battery, you can either use args.battery = "BAT*" or args.batteries = {"BAT*"}. Of course, if you have multiple batteries, you need to use the latter option."

> PS: can you try not defining battery to see how autodetection works on your machine?

I did that as well and I still get the same error.

Here is the [whole rc.lua](https://gist.github.com/wimstefan/4fd861582db54875a90806e8d625f6ac) as a reference - perhaps something else in my config is disturbing the new setup.

**Comment by lcpz** [comment]
Add back `battery`, and add `ac` as well, but don't use `BAT*` or `AC*`, use the directories in `/sys/class/power_supply/`. By the way, give me also the output of this command:

```shell
ls /sys/class/power_supply/
```

**Comment by wimstefan** [comment]
OK I've added back `battery` and added `ac` as suggested ... the changes can be seen in the gist.

> ls /sys/class/power_supply/

`ADP1  BAT1`

**Comment by lcpz** [comment]
The `nil` was referring to a missing variable. Thanks to you, I've fixed 3 issues.

It should be working now.

**Comment by wimstefan** [comment]
I'm happy to hear that I indirectly could help a bit :)

After pulling the latest commit there is indeed some progress ... now I'm getting a different error message ;-)
``` lua
error while running function!
stack traceback:
	[C]: in function 'error'
	/usr/share/awesome/lib/gears/object.lua:164: in function </usr/share/awesome/lib/gears/object.lua:146>
	/usr/share/awesome/lib/wibox/widget/base.lua:484: in function 'drill'
	/usr/share/awesome/lib/wibox/widget/base.lua:495: in function 'drill'
	/usr/share/awesome/lib/wibox/widget/base.lua:495: in function 'drill'
	/usr/share/awesome/lib/wibox/widget/base.lua:531: in function 'setup'
	/home/swimmer/.config/awesome/rc.lua:598: in function 'func'
	/usr/share/awesome/lib/awful/screen.lua:438: in function 'connect_for_each_screen'
	/home/swimmer/.config/awesome/rc.lua:538: in main chunk
error: /usr/share/awesome/lib/gears/object.lua:164: Cannot set 'batteries' on wibox.widget.textbox (table: 0x55f29c1d6a60) because it is read-only
```

That's happening both with `battery` and `ac` defined or not.

**Comment by lcpz** [comment]
It happens if you comment [this line](https://gist.github.com/wimstefan/4fd861582db54875a90806e8d625f6ac#file-rc-lua-L623)?

It happens if you set `battery="BAT1", ac="ADP1"` instead of using other variables?

Apart from this, the only possible cause is that I've moved `batteries,ac` from local [here](https://github.com/lcpz/lain/commit/89ae5308061ac828b4f5002ba77c069585b1e088#diff-eacfe07f3cb572b249327841b607e6ddL28) to `bat` table.

Also, can you try using Lua version 5.3.5?

@elv13 Sorry to bother, but what can cause a read-only issue within `gears`? it's the first time I see it.

**Comment by wimstefan** [comment]
* Luca CPZ <notifications@github.com> [2018-07-31 17:39]:
> It happens if you comment this line?

No it does not happen ...

> It happens if you set battery="BAT1", ac="ADP1" instead of using other variables?

Yes it happens as well if I set the values directly.

> Apart from this, the only possible cause is that I've moved batteries,ac from local here to bat table.
> 
> Also, can you try using Lua version 5.3.5?

That's unfortunately not possible since I'm running Gentoo ...

**Comment by lcpz** [comment]
I can put those variables back to local again, but I'd like to understand why it happens first.

**Comment by wimstefan** [comment]
OK. I presume I can't do anything at the moment? Please let me know if you want me to test something ...

Thanks for all your efforts!

**Comment by lcpz** [comment]
@wimstefan Try again with latest commit. I reverted.

**Comment by wimstefan** [comment]
It works on all my computers running awesomewm (2 laptops & 1 desktop) 😄
Thank you so much for your work!!!

**Comment by Elv13** [comment]
> @Elv13 Sorry to bother, but what can cause a read-only issue within gears? it's the first time I see it.

Sorry, I am on vacation AFK. Read-only properties are when there is an explicit getter but no explicit setter.

```lua

local o = gears.object {enable_properties=true}

local methods = {}

function methods:get_foo()
    return "bar"
end

gears.table.crush(o, methods, true)

print(o.foo)

>>> bar

o.foo = "baz"

>>> Cannot set 'foo' on gears.object (table: 0x55f29c1d6a60) because it is read-only

function methods:set_foo(value)
    self._foo = value
end

function methods:get_foo()
    return self._foo or "bar"
end

gears.table.crush(o, methods, true)

o.foo = "baz"

print(o.foo)

>>> baz
```
